apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-dir-manifest
spec:
  destination:
    namespace: directory
    server: https://kubernetes.default.svc
  project: default
  source:
          #    directory:
          #      exclude: 'service.yml'
          #      include: '{serviceaccount.yml,service.yml}'
          #      recurse: true
    path: argocd-advanced-v01/directoryOfManifests
    repoURL: https://github.com/shahid430/argocd-advanced-v01.git
    targetRevision: master
