apiVersion: v2
name: music
description: A Helm chart for Music service

type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies: 
  - name: postgresql 
    version: 15.5.28 
    repository: "https://charts.bitnami.com/bitnami"
