apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-app-01
spec:
  project: default
  source:
    path: helm/nginx
    repoURL: https://github.com/shahid430/argocd-advanced-v01.git
    targetRevision: master
    helm:
      releaseName: argocd-my-first-app
      parameters:
        - name: "replicaCount"
          value: "5"  # Corrected indentation
  destination:
    server: https://kubernetes.default.svc
    namespace: default

