apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-first-app
spec:
  project: default
  source:
    repoURL: https://github.com/shahid430/argocd-advanced-v01.git
    targetRevision: HEAD
    path: argocd-advanced-v01/helm/nginx
  destination:
    server: https://kubernetes.default.svc
    namespace: default
