apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
  name: {{ .Chart.Name }}
spec:
  ports:
    - name: http
      port: 80  # This is the port the service will expose (you can change it to another value if necessary)
      targetPort: {{ .Values.image.containerPort }}  # The container port from values.yml
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
  type: ClusterIP  # You can change this to NodePort, LoadBalancer, etc. depending on your requirements

